# Generated by Django 5.2.5 on 2025-10-01 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='SignUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(max_length=20)),
                ('email', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=8)),
                ('repeat_password', models.CharField(max_length=20)),
                ('role', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productname', models.TextField()),
                ('origin', models.TextField()),
                ('contact', models.IntegerField()),
                ('quality', models.CharField(blank=True, choices=[('A', 'Grade A'), ('B', 'Grade B'), ('C', 'Grade C')], max_length=10)),
                ('quantity', models.IntegerField()),
                ('costprice_unitcost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('costprice', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('date', models.DateField(null=True)),
                ('warehouse', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customername', models.TextField()),
                ('producttype', models.CharField(max_length=20)),
                ('quantity', models.IntegerField()),
                ('sellingprice_unitcost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('sellingprice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transportfare', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('transport_offered', models.BooleanField(default=True)),
                ('paymentmethod', models.CharField(max_length=10)),
                ('date', models.DateField(null=True)),
                ('totalprice', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_paid', models.BooleanField()),
                ('salesagentname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.signup')),
                ('productname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.stock')),
            ],
        ),
    ]
